CREATE TABLE posts(
	id SMALLINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	titulo VARCHAR(100) NOT NULL,
	texto TEXT NOT NULL,
	resumo TEXT NOT NULL,
    imagem VARCHAR(40) NOT NULL,
    usuario_id SMALLINT NOT NULL
);